import product1 from '../../images/MakkanKarhai.jpg';
import product2 from '../../images/MuttonHandi.jpg';
import product3 from '../../images/BBQ.jpg';
import product4 from '../../images/WhiteQorma.jpg';

import sweet1 from '../../images/sweet3.jpg';
import sweet2 from '../../images/sweet-2.jpg';
import sweet3 from '../../images/sweet-3.jpg';

export const productData = [
  {
    img: product2,
    alt: 'Mutton karahi',
    name: 'Mutton karahi',
    desc: 'A savory Pakistani dish with mutton cooked in a karahi (wok) with aromatic spices.',
    price: '65.99 AED',
    button: 'Add to Cart',
  },
  {
    img: product3,
    alt: 'BBQ',
    name: 'BBQ',
    desc: 'An exquisite assortment of grilled and barbecued meats, marinated to perfection and served with a selection of flavorful sauces.',
    price: '59.99 AED',
    button: 'Add to Cart',
  },
  {
    img: product1,
    alt: 'Mutton Handi',
    name: 'Mutton Handi',
    desc: 'A flavorful Pakistani dish with mutton cooked in a traditional handi (clay pot).',
    price: '59.99 AED',
    button: 'Add to Cart',
  },
  {
    img: product4,
    alt: 'Mutton white korma',
    name: 'Mutton white korma',
    desc: 'A creamy and mild Pakistani dish with mutton cooked in a white korma sauce.',
    price: '78.99 AED',
    button: 'Add to Cart',
  },
];
export const DinnerAndLunchItems = [
  {
    img: 'product1.jpg',
    alt: 'Mutton karahi',
    name: 'Mutton karahi',
    desc: 'A savory Pakistani dish with mutton cooked in a karahi (wok) with aromatic spices.',
    price: '65.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product2.jpg',
    alt: 'Mutton Handi',
    name: 'Mutton Handi',
    desc: 'A flavorful Pakistani dish with mutton cooked in a traditional handi (clay pot).',
    price: '59.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product3.jpg',
    alt: 'Mutton Achari',
    name: 'Mutton Achari',
    desc: 'A tangy and spicy Pakistani dish with mutton marinated in pickling spices.',
    price: '68.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product4.jpg',
    alt: 'Mutton korma',
    name: 'Mutton korma',
    desc: 'A rich and creamy Pakistani dish with mutton cooked in a flavorful korma sauce.',
    price: '74.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product5.jpg',
    alt: 'Mutton tawwa champ',
    name: 'Mutton tawwa champ',
    desc: 'Tender and succulent mutton chops cooked to perfection on a tawwa (griddle).',
    price: '82.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product6.jpg',
    alt: 'Mutton keema',
    name: 'Mutton keema',
    desc: 'A delicious Pakistani dish made with minced mutton and aromatic spices.',
    price: '55.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product7.jpg',
    alt: 'Mutton chop handi',
    name: 'Mutton chop handi',
    desc: 'A delightful dish with mutton chops cooked in a handi (clay pot) with spices.',
    price: '62.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product8.jpg',
    alt: 'Mutton white korma',
    name: 'Mutton white korma',
    desc: 'A creamy and mild Pakistani dish with mutton cooked in a white korma sauce.',
    price: '78.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product9.jpg',
    alt: 'Mutton pashawri',
    name: 'Mutton pashawri',
    desc: 'A traditional Pakistani dish with mutton cooked in a Peshawari style.',
    price: '69.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product10.jpg',
    alt: 'Mutton phindi',
    name: 'Mutton phindi',
    desc: 'A flavorful Pakistani dish with mutton cooked with lotus stem (phindi) and spices.',
    price: '67.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product11.jpg',
    alt: 'Mutton karyla',
    name: 'Mutton karyla',
    desc: 'A delicious Pakistani dish with mutton and bitter gourd (karyla) cooked together.',
    price: '64.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product12.jpg',
    alt: 'Mutton makhni',
    name: 'Mutton makhni',
    desc: 'A rich and creamy dish with mutton cooked in a buttery tomato sauce.',
    price: '76.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'product13.jpg',
    alt: 'Mutton dall mix',
    name: 'Mutton dall mix',
    desc: 'A flavorful Pakistani dish with mutton and mixed lentils cooked together.',
    price: '58.99 AED',
    button: 'Add to Cart',
  },
  {
    img: 'bbq.jpg',
    alt: 'BBQ',
    name: 'BBQ',
    desc: 'An exquisite assortment of grilled and barbecued meats, marinated to perfection and served with a selection of flavorful sauces.',
    price: '59.99 AED',
  },
];

export const SweetsItems = [
  {
    img: 'sweets1.jpg',
    alt: 'Rasgula',
    name: 'Rasgula',
    desc: 'A spongy and sweet dessert made from cottage cheese balls soaked in sugar syrup.',
    price: '10.99 AED',
    button: 'Order Now',
  },
  {
    img: 'sweets2.jpg',
    alt: 'Gulabjaman',
    name: 'Gulabjaman',
    desc: 'Delicious deep-fried dumplings soaked in fragrant sugar syrup.',
    price: '12.99 AED',
    button: 'Order Now',
  },
  {
    img: 'sweets3.jpg',
    alt: 'Barfi',
    name: 'Barfi',
    desc: 'A rich and creamy fudge-like sweet made with condensed milk and various flavors.',
    price: '8.99 AED',
    button: 'Order Now',
  },
  {
    img: 'sweets4.jpg',
    alt: 'Lado',
    name: 'Lado',
    desc: 'Traditional round-shaped sweet made with roasted flour, ghee, and sugar.',
    price: '9.99 AED',
    button: 'Order Now',
  },
  {
    img: 'sweets5.jpg',
    alt: 'Patisa',
    name: 'Patisa',
    desc: 'A flaky and crispy sweet made with layers of sugar-coated dough.',
    price: '11.99 AED',
    button: 'Order Now',
  },
  {
    img: 'sweets6.jpg',
    alt: 'Jalebi',
    name: 'Jalebi',
    desc: 'Orange spiral-shaped sweet made from deep-fried batter soaked in sugar syrup.',
    price: '10.99 AED',
    button: 'Order Now',
  },
  {
    img: 'sweets7.jpg',
    alt: 'Gajjar Halwa',
    name: 'Gajjar Halwa',
    desc: 'A delectable sweet dish made from grated carrots cooked in milk and sugar.',
    price: '14.99 AED',
    button: 'Order Now',
  },
  {
    img: 'sweets8.jpg',
    alt: 'Rasmalai',
    name: 'Rasmalai',
    desc: 'Soft and spongy cottage cheese dumplings served in a creamy milk syrup.',
    price: '13.99 AED',
    button: 'Order Now',
  },
  {
    img: 'sweets9.jpg',
    alt: 'Falooda',
    name: 'Falooda',
    desc: 'A refreshing dessert with vermicelli, basil seeds, ice cream, and flavored milk.',
    price: '15.99 AED',
    button: 'Order Now',
  },
  {
    img: 'sweets10.jpg',
    alt: 'Kheer',
    name: 'Kheer',
    desc: 'A classic rice pudding made with milk, rice, and sweetened with sugar or jaggery.',
    price: '9.99 AED',
    button: 'Order Now',
  },
  {
    img: 'sweets11.jpg',
    alt: 'Custard',
    name: 'Custard',
    desc: 'A creamy and smooth dessert made with milk, eggs, sugar, and flavored with vanilla.',
    price: '8.99 AED',
    button: 'Order Now',
  },
  {
    img: 'sweets12.jpg',
    alt: 'Fruit Chat',
    name: 'Fruit Chat',
    desc: 'A refreshing fruit salad mixed with spices and tangy chutneys.',
    price: '12.99 AED',
    button: 'Order Now',
  },
];

export const BreakFastItems = [
  {
    img: 'product3',
    alt: 'Alu Pratha',
    name: 'Alu Pratha',
    desc: 'A delicious Pakistani flatbread stuffed with spiced potato filling.',
    price: '21.99 AED',
  },
  {
    img: 'product3',
    alt: 'Sada Pratha',
    name: 'Sada Pratha',
    desc: 'A plain and simple Pakistani flatbread, best served with curries and chutneys.',
    price: '17.99 AED',
  },
  {
    img: 'product3',
    alt: 'Muli Pratha',
    name: 'Muli Pratha',
    desc: 'A flavorful Pakistani flatbread stuffed with seasoned radish.',
    price: '23.99 AED',
  },
  {
    img: 'product3',
    alt: 'Methi Pratha',
    name: 'Methi Pratha',
    desc: 'A Pakistani flatbread made with fenugreek leaves, rich in flavor.',
    price: '20.99 AED',
  },
  {
    img: 'product3',
    alt: 'Ghobi Pratha',
    name: 'Ghobi Pratha',
    desc: 'A Pakistani flatbread filled with spiced cauliflower, a delightful choice.',
    price: '24.99 AED',
  },
  {
    img: 'product3',
    alt: 'Sada Nan',
    name: 'Sada Nan',
    desc: 'A simple and soft Pakistani leavened bread, perfect for any curry.',
    price: '12.99 AED',
  },
  {
    img: 'product3',
    alt: 'Alu Nan',
    name: 'Alu Nan',
    desc: 'A Pakistani nan bread stuffed with spiced potatoes, a favorite of many.',
    price: '17.99 AED',
  },
  {
    img: 'product3',
    alt: 'Zatar Nan',
    name: 'Zatar Nan',
    desc: 'A delightful Pakistani nan bread seasoned with zatar, a unique taste.',
    price: '21.99 AED',
  },
  {
    img: 'product3',
    alt: 'Chiken Cheez Nan',
    name: 'Chiken Cheez Nan',
    desc: 'A scrumptious Pakistani nan bread with chicken and cheese filling.',
    price: '28.99 AED',
  },
  {
    img: 'product3',
    alt: 'Roogni Nan',
    name: 'Roogni Nan',
    desc: 'A special Pakistani nan bread garnished with sesame seeds.',
    price: '24.99 AED',
  },
  {
    img: 'product3',
    alt: 'Sada Nan',
    name: 'Sada Nan',
    desc: 'A simple and soft Pakistani leavened bread, perfect for any curry.',
    price: '12.99 AED',
  },
  {
    img: 'product3',
    alt: 'Sada Roti',
    name: 'Sada Roti',
    desc: 'A traditional Pakistani unleavened flatbread, a staple in many meals.',
    price: '14.99 AED',
  },
  {
    img: 'product3',
    alt: 'Misri Roti',
    name: 'Misri Roti',
    desc: 'A sweet Pakistani flatbread made with sugar crystals, a delightful treat.',
    price: '16.99 AED',
  },
  {
    img: 'product3',
    alt: 'Halwa Poori',
    name: 'Halwa Poori',
    desc: 'A classic Pakistani breakfast combination, consisting of halwa and poori.',
    price: '35.99 AED',
  },
  {
    img: 'product3',
    alt: 'Beef Paya',
    name: 'Beef Paya',
    desc: 'A hearty Pakistani soup made with beef trotters, rich and flavorful.',
    price: '38.99 AED',
  },
  {
    img: 'product3',
    alt: 'Mutton Paya',
    name: 'Mutton Paya',
    desc: 'A delicious and nutritious Pakistani soup made with mutton trotters.',
    price: '42.99 AED',
  },
  {
    img: 'product3',
    alt: 'Kofta',
    name: 'Kofta',
    desc: 'A Pakistani dish with spiced meatballs cooked in a flavorful sauce.',
    price: '29.99 AED',
  },
  {
    img: 'product3',
    alt: 'Haleem',
    name: 'Haleem',
    desc: 'A popular Pakistani dish made with meat, lentils, and wheat, slow-cooked to perfection.',
    price: '49.99 AED',
  },
  {
    img: 'product3',
    alt: 'Nehari',
    name: 'Nehari',
    desc: 'A traditional Pakistani stew made with slow-cooked meat and aromatic spices.',
    price: '44.99 AED',
  },
  {
    img: 'product3',
    alt: 'Chicken Chana',
    name: 'Chicken Chana',
    desc: 'A flavorful Pakistani dish with chicken and chickpeas, a delightful combination.',
    price: '36.99 AED',
  },
  {
    img: 'product3',
    alt: 'White Chana',
    name: 'White Chana',
    desc: 'A Pakistani dish made with tender chickpeas cooked in a spiced gravy.',
    price: '33.99 AED',
  },
  {
    img: 'product3',
    alt: 'Veg',
    name: 'Veg',
    desc: 'A hearty and nutritious Pakistani vegetarian dish, perfect for veggie lovers.',
    price: '35.99 AED',
  },
  {
    img: 'product3',
    alt: 'Daal Fry',
    name: 'Daal Fry',
    desc: 'A comforting Pakistani dish made with fried lentils and aromatic spices.',
    price: '24.99 AED',
  },
  {
    img: 'product3',
    alt: 'Egg Fry',
    name: 'Egg Fry',
    desc: 'A simple and delicious Pakistani egg dish, easy to prepare and delightful to eat.',
    price: '21.99 AED',
  },
  {
    img: 'product3',
    alt: 'Egg Omelette',
    name: 'Egg Omelette',
    desc: 'A classic omelette made with eggs and your choice of fillings, popular in Pakistan.',
    price: '14.99 AED',
  },
];

export const productDataTwo = [
  {
    img: sweet2,
    alt: 'Donuts',
    name: 'Doughlicious',
    desc: 'Belgian chocolate glazed donuts covered in icing with sprinkles on top',
    price: '$9.99',
    button: 'Add to Cart',
  },
  {
    img: sweet3,
    alt: 'Ice Cream',
    name: 'Caramel Wonder',
    desc: 'Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick',
    price: '$12.99',
    button: 'Add to Cart',
  },
  {
    img: sweet1,
    alt: 'Brownie',
    name: 'Brownie Bunch',
    desc: 'Double fudge brownie squares topped with white chocolate pieces and macadamia nuts',
    price: '$9.99',
    button: 'Add to Cart',
  },
  {
    img: sweet1,
    alt: 'Brownie',
    name: 'Brownie Bunch',
    desc: 'Double fudge brownie squares topped with white chocolate pieces and macadamia nuts',
    price: '$9.99',
    button: 'Add to Cart',
  },
  {
    img: sweet1,
    alt: 'Brownie',
    name: 'Brownie Bunch',
    desc: 'Double fudge brownie squares topped with white chocolate pieces and macadamia nuts',
    price: '$9.99',
    button: 'Add to Cart',
  },
  {
    img: sweet1,
    alt: 'Brownie',
    name: 'Brownie Bunch',
    desc: 'Double fudge brownie squares topped with white chocolate pieces and macadamia nuts',
    price: '$9.99',
    button: 'Add to Cart',
  },
  {
    img: sweet1,
    alt: 'Brownie',
    name: 'Brownie Bunch',
    desc: 'Double fudge brownie squares topped with white chocolate pieces and macadamia nuts',
    price: '$9.99',
    button: 'Add to Cart',
  },
];
